# fly.toml app configuration file generated for car-rental-app-weathered-tree-7075 on 2023-12-26T23:12:29+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "car-rental-app-weathered-tree-7075"
primary_region = "sin"

[build]

[env]
  DATABASE_ENVIRONMENT = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[deploy]
  release_command = "npm run db-setup"
